name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build for Linux
      run: npm run build:linux-zip

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Pokerogue-Linux
        path: ./dist/Pokerogue-Linux.zip

  build-windows:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build for Windows (NSIS)
      run: npm run build:win-nsis

    - name: Upload Windows NSIS Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Pokerogue-Installer
        path: ./dist/Pokerogue-Installer.exe

    - name: Build for Windows (ZIP)
      run: npm run build:win-zip

    - name: Upload Windows ZIP Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Pokerogue-Win
        path: ./dist/Pokerogue-Win.zip

  create-release:
    runs-on: ubuntu-latest
    needs: [build, build-windows]

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Get Linux Artifact
      uses: actions/download-artifact@v2
      with:
        name: Pokerogue-Linux
        path: ./dist

    - name: Get Windows NSIS Artifact
      uses: actions/download-artifact@v2
      with:
        name: Pokerogue-Installer
        path: ./dist

    - name: Get Windows ZIP Artifact
      uses: actions/download-artifact@v2
      with:
        name: Pokerogue-Win
        path: ./dist

    - name: Upload Linux Artifact to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/Pokerogue-Linux.zip
        asset_name: Pokerogue-Linux.zip
        asset_content_type: application/zip

    - name: Upload Windows NSIS Artifact to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/Pokerogue-Installer.exe
        asset_name: Pokerogue-Installer.exe
        asset_content_type: application/octet-stream

    - name: Upload Windows ZIP Artifact to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/Pokerogue-Win.zip
        asset_name: Pokerogue-Win.zip
        asset_content_type: application/zip

    - name: Finalize Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/*.zip
        asset_name: Pokerogue-${{ github.run_number }}.zip
        asset_content_type: application/zip
