name: CI

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build for Linux
        run: npm run build

      - name: Rename and Archive Linux artifacts
        run: |
          mv dist dist-linux
          zip -r -9 pokerogue_linux.zip dist-linux

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pokerogue_linux
          path: pokerogue_linux.zip

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build for Windows
        run: npm run build

      - name: Rename and Archive Windows artifacts
        run: |
          mv dist dist-windows
          Compress-Archive -Path .\dist-windows\* -DestinationPath pokerogue_windows.zip -Force

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pokerogue_windows
          path: pokerogue_windows.zip

  upload-artifacts:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux artifacts
        uses: actions/download-artifact@v2
        with:
          name: pokerogue_linux

      - name: Download Windows artifacts
        uses: actions/download-artifact@v2
        with:
          name: pokerogue_windows

