name: Build and Release

on:
  push:
#    branches:
#      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build for Linux
      run: npm run build:linux-zip

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Pokerogue-Linux
        path: ./dist/*.zip

    - name: Build for Linux (DEB)
      run: npm run build:linux-deb

    - name: Upload Linux DEB Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Pokerogue-Linux-DEB
        path: ./dist/*.deb

    - name: Build for Linux (RPM)
      run: npm run build:linux-rpm

    - name: Upload Linux RPM Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Pokerogue-Linux-RPM
        path: ./dist/*.rpm
  
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build for Windows (NSIS)
      run: npm run build:win-nsis

    - name: Upload Windows NSIS Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Pokerogue-Installer
        path: ./dist/Pokerogue-Installer.exe

    - name: Build for Windows (ZIP)
      run: npm run build:win-zip

    - name: Upload Windows ZIP Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Pokerogue-Win
        path: ./dist/Pokerogue-Win.zip
